site_name: Notes for DevOps
site_url: https://lastharbor.github.io/mkdocs-notes/
theme:
  name: material
site_author: Anton Kulakevich
copyright: Anton Kulakevich, AwesomeEduSPB
nav:
    - Home: index.md
    - About: About.md
    - DevOpsBasics:
            - Basics: Dev Ops Basics.md
            - Proxmox: Proxmox.md
