site_name: Notes for DevOps
site_url: https://lastharbor.github.io/mkdocs-notes/
docs_dir: ./docs

theme:
  name: material
  language: en
  palette:
    - scheme: light
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.indexes
    - content.code.copy

plugins:
  - search
  - gen_nav:
      enabled: true

extra_javascript:
  - js/auth_config.js
  - js/auth.js

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
